# Generated by Django 3.0 on 2022-07-06 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='nome',
            new_name='name',
        ),
    ]
