# Generated by Django 3.0 on 2022-07-06 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220705_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='name',
            new_name='nome',
        ),
    ]
